name: 📚 Docs

on:
  workflow_call:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 📚 Deploy docs
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'node'

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 📚 Generate docs
        run: pnpm run docs

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/api

      - name: 🚀 Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
